### PR TITLE
fix: Credential Service Staging - Resolve issue with page not loading and broken login [DEV-3162]

### PR DESCRIPTION
**Pull request by abdulla-ashurov**
- [x] Resolve issue with page not loading.
- [x] Fix broken login.

### CODE REVIEW

**Comment by ankurdotb** [comment]
Task linked: [DEV-3162 Credential Service Staging - Resolve issue with page not loading and broken login](https://app.clickup.com/t/6600954/DEV-3162)

**Review by Eengineer1 — CHANGES_REQUESTED** [review]
Thanks for looking into this.

I've left a comprehensive list of notes on why monkey patching is necessary for encryption conditions succeeding, until either @verida/encryption-utils removes their json stringify replacement or we get rid of verida functionality / packages altogether.

Could you restore it instead of removing it?

**Comment by abdulla-ashurov** [comment]
> Thanks for looking into this.
> 
> I've left a comprehensive list of notes on why monkey patching is necessary for encryption conditions succeeding, until either @verida/encryption-utils removes their json stringify replacement or we get rid of verida functionality / packages altogether.
> 
> Could you restore it instead of removing it?

Restored! ✅

**Review by anikitinDSR — DISMISSED** [review]

**Review by Eengineer1 — APPROVED** [review]
Approved with various enhancements.

Thanks!

**Pull request merged**
